In [20]:
import array as pArr
import numpy as np
import sympy as sym
import scipy as sc
import scipy.linalg as la
import matplotlib.pyplot as plt
import os
import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from Easy_Pretty_Math.Display_Math_Operations import *
# dmo_auto(status=True)
sym.init_printing(use_latex='mathjax', latex_mode='equation*')
# init_printing(pretty_print=True)
x, y, z, k, w = sym.symbols('x, y, z, k, w')

There are several ways to define linear matrixes in python.  Using Sympy, we define a matrix using the Sympy.Matrix class but elsewhere in python (Numpy,SciPy, ex) it is usually better to use np.arrays than matrixes.  Sympy is the primary way to convert code into classical math symbols in python and thus, is used extensively on the pages of this website.  Sypmy.Matrix's are not directly the same thing as Numpy Arrays but they can be converted, one into the other.

Below is a table of the differences between varies ways to represent sets of data in memory

<div>
<table align="left" class="MsoTableGrid" style="width:733px; border-collapse:collapse; border:none; margin-left:9px; margin-right:9px" width="733">
	<tbody>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:1px solid black; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:1px solid black; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">List</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:1px solid black; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Python Array</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:1px solid black; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Numpy Array</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:1px solid black; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Tuple</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:1px solid black; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Sympy Matrix</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:1px solid black; border-right:1px solid black; border-left:none" valign="top">
			<p align="center" style="text-align:center"><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Dictionary</span></font></font></span></span></p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Ordered</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Mutable</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Syntax</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">[ ]</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">arr.array([ ])</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">np.array([ ])</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">( )</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">sym.Matrix([ ])</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">{ }</span></font></font></span></span></p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Duplicates</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Type Mixing</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Kind of</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Need Declaration</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">X</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Memory</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">High</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Lower</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Lower</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Lower</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">High</span></font></font></span></span></p>
			</td>
		</tr>
		<tr>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:1px solid black" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Notes</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p>&nbsp;</p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">import array as arr</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">import numpy as np</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:105px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Can be used as keys</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:118px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">import sympy as sym</span></font></font></span></span></p>
			</td>
			<td style="border-bottom:1px solid black; width:92px; padding:0in 7px 0in 7px; border-top:none; border-right:1px solid black; border-left:none" valign="top">
			<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><font size="3"><font face="Times New Roman"><span style="font-size:12.0pt">Requires {key:value} pairs</span></font></font></span></span></p>
			</td>
		</tr>
	</tbody>
</table>
</div>


**Lists**

Most versatile, but not appropriate for math operations

In [9]:
["this",'is','a list',1234,{1,"things"},[1,2]]

['this', 'is', 'a list', 1234, {1, 'things'}, [1, 2]]

**Python Array**

Needs to be the same type and to specify such

In [10]:
pArr.array('i',[1,1,2,3,5,8,13])
pArr.array([1,3,'A',['something']]) #Won't work

array('i', [1, 1, 2, 3, 5, 8, 13])

TypeError: array() argument 1 must be a unicode character, not list

In [11]:
pArr.array([1,1,2,3,5,8,13]) #Also won't work

TypeError: array() argument 1 must be a unicode character, not list

**Numpy Array**

Numpy Arrays can have mixed types

In [12]:
np.array([1,3,'A',['something']]) 
n=np.array([[9,2,3],[4,5,6],[7,8,9]])
n
n*n
n@n
I=np.eye(3)
I
la.inv(n)

array([1, 3, 'A', list(['something'])], dtype=object)

array([[9, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[81,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

array([[110,  52,  66],
       [ 98,  81,  96],
       [158, 126, 150]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 0.125     , -0.25      ,  0.125     ],
       [-0.25      , -2.5       ,  1.75      ],
       [ 0.125     ,  2.41666667, -1.54166667]])

**Tuple**

Tuples cannot be mutated

In [19]:
t=(5,'t',"aert t r ",{1:"erdtyt"},[1,'yui'])
t
t[2]
t[0]*t[0]
t[2]=124

(5, 't', 'aert t r ', {1: 'erdtyt'}, [1, 'yui'])

'aert t r '

25

TypeError: 'tuple' object does not support item assignment

**Sympy Matrix**



In [22]:
m=sym.Matrix([[9,2,3],[4,5,'X'],[7,8,9]])
m
m*m
m@m
I=sym.eye(3)
I
m.inv()

⎡9  2  3⎤
⎢       ⎥
⎢4  5  X⎥
⎢       ⎥
⎣7  8  9⎦

⎡  110        52     2⋅X + 54 ⎤
⎢                             ⎥
⎢7⋅X + 56  8⋅X + 33  14⋅X + 12⎥
⎢                             ⎥
⎣  158       126     8⋅X + 102⎦

⎡  110        52     2⋅X + 54 ⎤
⎢                             ⎥
⎢7⋅X + 56  8⋅X + 33  14⋅X + 12⎥
⎢                             ⎥
⎣  158       126     8⋅X + 102⎦

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦

⎡ 134865 - 23976⋅X        17982          5994⋅X - 44955 ⎤
⎢─────────────────  ─────────────────  ─────────────────⎥
⎢971028 - 173826⋅X  971028 - 173826⋅X  971028 - 173826⋅X⎥
⎢                                                       ⎥
⎢ 2331⋅X - 11988         19980          3996 - 2997⋅X   ⎥
⎢────────────────   ────────────────   ──────────────── ⎥
⎢107892 - 19314⋅X   107892 - 19314⋅X   107892 - 19314⋅X ⎥
⎢                                                       ⎥
⎢      -27               -522                333        ⎥
⎢  ────────────       ────────────       ────────────   ⎥
⎣  2916 - 522⋅X       2916 - 522⋅X       2916 - 522⋅X   ⎦

**Dictionary**

Key:Value pairs

In [17]:
{'key':'value',1:1,'array':[1,2,3,'something'],"test":1,(1,3):{'something':"somethingElse"}}

{'key': 'value',
 1: 1,
 'array': [1, 2, 3, 'something'],
 'test': 1,
 (1, 3): {'something': 'somethingElse'}}