In [60]:
import array as pArr
import numpy as np
import sympy as sym
import scipy as sc
import scipy.linalg as la
import matplotlib.pyplot as plt
import os
import nbformat
from nbconvert.preprocessors import ExecutePreprocessor
from IPython.core.interactiveshell import InteractiveShell
from IPython.display import display, Math, Markdown
InteractiveShell.ast_node_interactivity = "all"
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
from Easy_Pretty_Math.Display_Math_Operations import *
init_printing(pretty_print=True)
# dmo_auto(status=True)
sym.init_printing(use_latex='mathjax', latex_mode='equation*')
x, y, z, k, w, m = sym.symbols('x, y, z, k, w, m')
def printmd(string):
    display(Markdown(string))

There are several ways to define linear matrices in python.  Using Sympy, we define a matrix using the Sympy.Matrix class but elsewhere in python (Numpy,SciPy, ex) it is usually better to use np.arrays than matrixes.  Sympy is the primary way to covert code into classical math symbols in python and thus, is used extensively on the pages of this website.  Sypmy.Matrix's are not directly the same thing as Numpy Arrays but they can be converted, one into the other.

**Adding matrices is fairly simple; you just add the corresponding entries (or 'cells') together**

\begin{equation*}
\left[
\begin{matrix}9 & 2 & 3 & 5 \\4 & 5 & 6 & 4 \\7 & 8 & 9 & 6 \\11 & 13 & 17 & 19 \end{matrix}
\right]
+
\left[
\begin{matrix}9 & 2 & 3 & 5 \\4 & 5 & 6 & 4 \\7 & 8 & 9 & 6 \\11 & 13 & 17 & 19 \end{matrix}
\right]
=
\left[\begin{matrix}18 & 4 & 6 & 10 \\8 & 10 & 12 & 8 \\14 & 16 & 18 & 12 \\22 & 26 & 34 & 38 \end{matrix}\right]
\end{equation*}

In [84]:
#Syntax of a Sympy matrix and adding
m=sym.Matrix([[9,2,3,' apples'],[4,5,6,4],[7,8,9,6],[11,13,17,19]])
m
m+m

⎡9   2   3   apples⎤
⎢                  ⎥
⎢4   5   6     4   ⎥
⎢                  ⎥
⎢7   8   9     6   ⎥
⎢                  ⎥
⎣11  13  17    19  ⎦

⎡18  4   6   2⋅apples⎤
⎢                    ⎥
⎢8   10  12     8    ⎥
⎢                    ⎥
⎢14  16  18     12   ⎥
⎢                    ⎥
⎣22  26  34     38   ⎦

**Adding matrices that are different sizes doesn't work**
\begin{equation*}
\left( \left[\begin{matrix}9 & 2 & 3 & apples\\4 & 5 & 6 & 4\\7 & 8 & 9 & 6\\11 & 13 & 17 & 19\end{matrix}\right]\  + \  \left[\begin{matrix}9 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\\11 & 13 & 17\end{matrix}\right]\right)=Doesn't \ work
\end{equation*}

In [87]:
m=sym.Matrix([[9,2,3,' apples'],[4,5,6,4],[7,8,9,6],[11,13,17,19]])
n=sym.Matrix([[9,2,3],[4,5,6],[7,8,9],[11,13,17]])
m
n
m+n

⎡9   2   3   apples⎤
⎢                  ⎥
⎢4   5   6     4   ⎥
⎢                  ⎥
⎢7   8   9     6   ⎥
⎢                  ⎥
⎣11  13  17    19  ⎦

⎡9   2   3 ⎤
⎢          ⎥
⎢4   5   6 ⎥
⎢          ⎥
⎢7   8   9 ⎥
⎢          ⎥
⎣11  13  17⎦

ShapeError: Matrix size mismatch: (4, 4) + (4, 3)

** Multiplying matrices is a little more involved **

*In sympy matrices, \* and @ are the same thing*

To multiply two or more matrces
\begin{equation*}
\left( \left[\begin{matrix}9 & 2 & 3 & 5\\4 & 5 & 6 & 4\\7 & 8 & 9 & 6\\11 & 13 & 17 & 19\end{matrix}\right]@ \  \left[\begin{matrix}9 & 34 & -9\\-5 & 0.01 & 50\\8 & 1.25 & 8\\15 & 17 & -7\end{matrix}\right]\right)=
\left[\begin{matrix}170 & 394.77 & 8\\119 & 211.55 & 234\\185 & 351.33 & 367\\455 & 718.38 & 554\end{matrix}\right]
\end{equation*}
\begin{equation*}
\left( \left( \left[\begin{matrix}9\\4\\7\\11\end{matrix}\right]@ \  \left[\begin{matrix}9 & 34 & -9\end{matrix}\right]\right)+ \  \left( \left[\begin{matrix}2\\5\\8\\13\end{matrix}\right], \  \left[\begin{matrix}-5 & 0.01 & 50\end{matrix}\right]\right), \  \left( \left[\begin{matrix}3\\6\\9\\17\end{matrix}\right], \  \left[\begin{matrix}8 & 1.25 & 8\end{matrix}\right]\right), \  \left( \left[\begin{matrix}5\\4\\6\\19\end{matrix}\right], \  \left[\begin{matrix}15 & 17 & -7\end{matrix}\right]\right)\right)
\end{equation*}

In [203]:
m=sym.Matrix([[9,2,3,5],[4,5,6,4],[7,8,9,6],[11,13,17,19]])
n=sym.Matrix([[9,34,-9],[-5,.01,50],[8,1.25,8],[15,17,-7]])
o=sym.Matrix([[9],[-5],[8],[15]])
p=sym.Matrix([9])
#In sympy matrices, * and @ are the same thing

m[0:4,2:3],n[2:3,0:4]
(m[0:4,0:1]@n[0:1,0:4])+(m[0:4,1:2]@n[1:2,0:4])+(m[0:4,2:3]@n[2:3,0:4])+(m[0:4,3:4]@n[3:4,0:4])
m,n
m@o
m@n
# print_latex((m,n))
# print_latex((m[0:4,0:1],n[0:4,0:1]))
# print_latex(((m[0:4,0:1],n[0:1,0:4]),(m[0:4,1:2],n[1:2,0:4]),(m[0:4,2:3],n[2:3,0:4]),(m[0:4,3:4],n[3:4,0:4])))
print_latex((m@n))

⎛⎡3 ⎤              ⎞
⎜⎢  ⎥              ⎟
⎜⎢6 ⎥              ⎟
⎜⎢  ⎥, [8  1.25  8]⎟
⎜⎢9 ⎥              ⎟
⎜⎢  ⎥              ⎟
⎝⎣17⎦              ⎠

⎡170  394.77   8 ⎤
⎢                ⎥
⎢119  211.55  234⎥
⎢                ⎥
⎢185  351.33  367⎥
⎢                ⎥
⎣455  718.38  554⎦

⎛⎡9   2   3   5 ⎤  ⎡9    34   -9⎤⎞
⎜⎢              ⎥  ⎢            ⎥⎟
⎜⎢4   5   6   4 ⎥  ⎢-5  0.01  50⎥⎟
⎜⎢              ⎥, ⎢            ⎥⎟
⎜⎢7   8   9   6 ⎥  ⎢8   1.25  8 ⎥⎟
⎜⎢              ⎥  ⎢            ⎥⎟
⎝⎣11  13  17  19⎦  ⎣15   17   -7⎦⎠

⎡170⎤
⎢   ⎥
⎢119⎥
⎢   ⎥
⎢185⎥
⎢   ⎥
⎣455⎦

⎡170  394.77   8 ⎤
⎢                ⎥
⎢119  211.55  234⎥
⎢                ⎥
⎢185  351.33  367⎥
⎢                ⎥
⎣455  718.38  554⎦

\left[\begin{matrix}170 & 394.77 & 8\\119 & 211.55 & 234\\185 & 351.33 & 367\\455 & 718.38 & 554\end{matrix}\right]


*But in numpy arrays, this is not the case*

In [170]:
#But in numpy arrays, this is not the case:
m=np.array([[9,2,3,5],[4,5,6,4],[7,8,9,6],[11,13,17,19]])
n=np.array([[9,34,-9],[-5,.01,50],[8,1.25,8],[15,17,-7]])
o=np.array([[9],[-5],[8],[15]])
'm,n,o'
m,n,o
'm@o'
m@o
'm@n'
m@n
'm*o'
m*o
'm*n'
m*n

'm,n,o'

(array([[ 9,  2,  3,  5],
        [ 4,  5,  6,  4],
        [ 7,  8,  9,  6],
        [11, 13, 17, 19]]),
 array([[ 9.00e+00,  3.40e+01, -9.00e+00],
        [-5.00e+00,  1.00e-02,  5.00e+01],
        [ 8.00e+00,  1.25e+00,  8.00e+00],
        [ 1.50e+01,  1.70e+01, -7.00e+00]]),
 array([[ 9],
        [-5],
        [ 8],
        [15]]))

'm@o'

array([[170],
       [119],
       [185],
       [455]])

'm@n'

ShapeError: Matrix size mismatch.